spring.application.name=thindesk
spring.config.import=optional:file:.env[.properties]

spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=${MONGODB_DATABASE:thindesk}
spring.data.mongodb.auto-index-creation=true

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false

logging.level.com.pfc=DEBUG
